"use client";

import { useState } from "react";
import {
  Brain,
  Clock,
  Target,
  Sparkles,
  Loader2,
  AlertTriangle,
  BarChart3,
  CheckCircle,
  Timer,
  ShieldCheck,
} from "lucide-react";

export default function Home() {
  const [task, setTask] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);

  const analyzeTask = async () => {
    if (!task.trim()) {
      alert("Please enter your task.");
      return;
    }

    setLoading(true);

    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ task }),
      });

      const data = await response.json();

      setResult(data.result);
    } catch (error) {
      console.error(error);
      setResult("Something went wrong while analyzing.");
    }

    setLoading(false);
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-indigo-950 via-blue-800 to-cyan-500">

      <div className="max-w-7xl mx-auto px-6 py-10">

        {/* HERO */}

        <div className="text-center text-white">

          <div className="flex justify-center">

            <div className="bg-white/20 backdrop-blur-lg rounded-full p-6 shadow-2xl">

              <Brain size={55} />

            </div>

          </div>

          <h1 className="text-6xl font-extrabold mt-6">
            Deadline Guardian AI
          </h1>

          <p className="text-blue-100 text-xl mt-5 max-w-3xl mx-auto">
            AI-powered productivity assistant that analyzes your tasks,
            estimates effort, prioritizes work, and helps you finish
            before deadlines.
          </p>

        </div>

        {/* FEATURE CARDS */}

        <div className="grid md:grid-cols-4 gap-6 mt-14">

          <div className="bg-white rounded-2xl shadow-xl p-6 hover:scale-105 transition">

            <Clock className="text-blue-600 mb-3" size={35} />

            <h2 className="font-bold text-lg">
              Smart Time Estimate
            </h2>

            <p className="text-gray-600 mt-2">
              AI predicts how much time your task may require.
            </p>

          </div>

          <div className="bg-white rounded-2xl shadow-xl p-6 hover:scale-105 transition">

            <Target className="text-red-500 mb-3" size={35} />

            <h2 className="font-bold text-lg">
              Priority Detection
            </h2>

            <p className="text-gray-600 mt-2">
              Instantly identify the most important work.
            </p>

          </div>

          <div className="bg-white rounded-2xl shadow-xl p-6 hover:scale-105 transition">

            <Sparkles className="text-yellow-500 mb-3" size={35} />

            <h2 className="font-bold text-lg">
              AI Suggestions
            </h2>

            <p className="text-gray-600 mt-2">
              Get productivity advice generated by AI.
            </p>

          </div>

          <div className="bg-white rounded-2xl shadow-xl p-6 hover:scale-105 transition">

            <ShieldCheck className="text-green-600 mb-3" size={35} />

            <h2 className="font-bold text-lg">
              Deadline Protection
            </h2>

            <p className="text-gray-600 mt-2">
              Stay ahead of deadlines with smart planning.
            </p>

          </div>

        </div>

        {/* MAIN INPUT CARD */}

        <div className="bg-white rounded-3xl shadow-2xl mt-14 p-8">

          <h2 className="text-3xl font-bold text-center mb-6">
            Enter Your Task
          </h2>

          <textarea
            rows={6}
            value={task}
            onChange={(e) => setTask(e.target.value)}
            placeholder="Example: My MCA project submission is due in 3 days and I have completed only 20%."
            className="w-full rounded-xl border-2 border-blue-200 p-4 text-lg focus:border-blue-600 outline-none"
          />

          <button
            onClick={analyzeTask}
            disabled={loading}
            className="mt-6 w-full bg-gradient-to-r from-blue-600 to-indigo-700 text-white py-4 rounded-xl text-lg font-bold flex justify-center items-center gap-3 hover:scale-[1.02] transition"
          >
            {loading ? (
              <>
                <Loader2 className="animate-spin" size={22} />
                Analyzing...
              </>
            ) : (
              <>
                <Brain size={22} />
                Analyze Task
              </>
            )}
          </button>
                    {result && (
            <div className="mt-10">

              {/* AI Report */}

              <div className="bg-slate-50 border rounded-2xl shadow-lg p-6">

                <h2 className="text-3xl font-bold text-blue-700 flex items-center gap-3 mb-6">
                  <BarChart3 />
                  AI Analysis Report
                </h2>

                <div className="grid md:grid-cols-4 gap-4">

                  <div className="bg-red-50 border border-red-200 rounded-xl p-5">

                    <AlertTriangle className="text-red-500 mb-2" />

                    <h3 className="font-bold text-red-600">
                      Priority
                    </h3>

                    <p className="mt-2 font-semibold">
                      High
                    </p>

                  </div>

                  <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-5">

                    <Target className="text-yellow-600 mb-2" />

                    <h3 className="font-bold text-yellow-700">
                      Difficulty
                    </h3>

                    <p className="mt-2 font-semibold">
                      Medium
                    </p>

                  </div>

                  <div className="bg-blue-50 border border-blue-200 rounded-xl p-5">

                    <Timer className="text-blue-600 mb-2" />

                    <h3 className="font-bold text-blue-700">
                      Estimated Hours
                    </h3>

                    <p className="mt-2 font-semibold">
                      4–6 Hours
                    </p>

                  </div>

                  <div className="bg-green-50 border border-green-200 rounded-xl p-5">

                    <Clock className="text-green-600 mb-2" />

                    <h3 className="font-bold text-green-700">
                      Urgency
                    </h3>

                    <p className="mt-2 font-semibold">
                      High
                    </p>

                  </div>

                </div>

                <div className="mt-8 bg-white border rounded-xl p-5 whitespace-pre-wrap leading-8">

                  {result}

                </div>

              </div>

              {/* Action Plan */}

              <div className="mt-8 bg-white rounded-2xl shadow-lg p-6">

                <h2 className="text-2xl font-bold text-green-700 flex items-center gap-3 mb-5">

                  <CheckCircle />

                  Suggested Action Plan

                </h2>

                <div className="space-y-4">

                  <div className="flex gap-3">
                    <CheckCircle className="text-green-600 mt-1" />
                    <p>Understand the task requirements completely.</p>
                  </div>

                  <div className="flex gap-3">
                    <CheckCircle className="text-green-600 mt-1" />
                    <p>Complete the core implementation first.</p>
                  </div>

                  <div className="flex gap-3">
                    <CheckCircle className="text-green-600 mt-1" />
                    <p>Test every important feature carefully.</p>
                  </div>

                  <div className="flex gap-3">
                    <CheckCircle className="text-green-600 mt-1" />
                    <p>Prepare documentation and final report.</p>
                  </div>

                  <div className="flex gap-3">
                    <CheckCircle className="text-green-600 mt-1" />
                    <p>Submit your project before the deadline.</p>
                  </div>

                </div>

              </div>

            </div>
          )}

        </div>

        <footer className="text-center text-white mt-12 pb-6">

  <h3 className="text-xl font-bold">
    🚀 Deadline Guardian AI
  </h3>

  <p className="opacity-80 mt-2">
    Built with Next.js • Gemini AI • Tailwind CSS
  </p>

  <p className="opacity-60 mt-2 text-sm">
    Developed for Hackathon 2026
  </p>

</footer>

</div>

</main>
);
}